import type { Incident } from './types';

/** 92 seed incidents — India-wide deforestation + heritage trees */
export const MOCK_INCIDENTS: Incident[] = [
  {
    "id": "00000000-0000-0000-0000-000000000001",
    "created_at": "2025-07-17T08:29:10.268Z",
    "lat": 19.076,
    "lng": 72.8777,
    "location_name": "Aarey Milk Colony",
    "state": "Maharashtra",
    "district": "Mumbai Suburban",
    "tree_count": 2147,
    "species": [
      "Teak",
      "Mango",
      "Banyan"
    ],
    "reason_category": "metro_rail",
    "reason_detail": "Mass tree felling for Metro Line 3 depot in urban forest patch",
    "project_name": "Mumbai Metro Line 3",
    "authority": "MMRCL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": "NGT/2019/001234",
    "source_url": "https://www.google.com/search?q=Aarey%20Milk%20Colony%20Mumbai%20Metro%20Line%203%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000002",
    "created_at": "2025-09-25T08:29:10.268Z",
    "lat": 12.9716,
    "lng": 77.5946,
    "location_name": "Bannerghatta Road Corridor",
    "state": "Karnataka",
    "district": "Bengaluru Urban",
    "tree_count": 890,
    "species": [
      "Neem",
      "Peepal"
    ],
    "reason_category": "road_widening",
    "reason_detail": "NH-48 widening through urban forest patches",
    "project_name": "NH-48 Six-Laning Bengaluru",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Bannerghatta%20Road%20Corridor%20NH-48%20Six-Laning%20Bengaluru%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000003",
    "created_at": "2025-04-28T08:29:10.268Z",
    "lat": 28.6139,
    "lng": 77.209,
    "location_name": "Central Ridge Forest",
    "state": "Delhi",
    "district": "New Delhi",
    "tree_count": 412,
    "species": [
      "Keekar",
      "Babul"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Landscaping for Central Vista redevelopment",
    "project_name": "Central Vista Avenue",
    "authority": "CPWD",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": "NGT/2021/000567",
    "source_url": "https://www.google.com/search?q=Central%20Ridge%20Forest%20Central%20Vista%20Avenue%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000004",
    "created_at": "2025-12-04T08:29:10.268Z",
    "lat": 23.2599,
    "lng": 77.4126,
    "location_name": "Kerwa Forest Range",
    "state": "Madhya Pradesh",
    "district": "Bhopal",
    "tree_count": 1560,
    "species": [
      "Sal",
      "Teak",
      "Bamboo"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Forest land diversion for smart city expansion",
    "project_name": "Bhopal Smart City Phase II",
    "authority": "BDA Bhopal",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kerwa%20Forest%20Range%20Bhopal%20Smart%20City%20Phase%20II%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000005",
    "created_at": "2025-01-18T08:29:10.268Z",
    "lat": 24.7136,
    "lng": 84.9833,
    "location_name": "Godda District Mining Belt",
    "state": "Jharkhand",
    "district": "Godda",
    "tree_count": 4800,
    "species": [
      "Sal",
      "Mahua"
    ],
    "reason_category": "mining",
    "reason_detail": "Forest clearance for thermal power plant coal mining",
    "project_name": "Adani Godda Thermal Power Plant",
    "authority": "Adani Power",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": "NGT/2020/000891",
    "source_url": "https://www.google.com/search?q=Godda%20District%20Mining%20Belt%20Adani%20Godda%20Thermal%20Power%20Plant%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000006",
    "created_at": "2023-02-18T08:29:10.268Z",
    "lat": 15.2993,
    "lng": 74.124,
    "location_name": "Mollem National Park Buffer",
    "state": "Goa",
    "district": "North Goa",
    "tree_count": 58900,
    "species": [
      "Teak",
      "Ironwood",
      "Xylopia"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Major Western Ghats forest diversion for transmission corridor",
    "project_name": "Goa-Tamnar Transmission Line",
    "authority": "POWERGRID",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": "NGT/2020/000456",
    "source_url": "https://www.google.com/search?q=Mollem%20National%20Park%20Buffer%20Goa-Tamnar%20Transmission%20Line%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000007",
    "created_at": "2025-08-26T08:29:10.268Z",
    "lat": 17.385,
    "lng": 78.4867,
    "location_name": "KBR National Park Buffer",
    "state": "Telangana",
    "district": "Hyderabad",
    "tree_count": 156,
    "species": [
      "Banyan",
      "Peepal"
    ],
    "reason_category": "metro_rail",
    "reason_detail": "Metro corridor near KBR Park buffer zone",
    "project_name": "Hyderabad Metro Rail Phase 2",
    "authority": "HMRL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": "NGT/2022/000345",
    "source_url": "https://www.google.com/search?q=KBR%20National%20Park%20Buffer%20Hyderabad%20Metro%20Rail%20Phase%202%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000008",
    "created_at": "2026-03-04T08:29:10.268Z",
    "lat": 26.2006,
    "lng": 92.9376,
    "location_name": "Kaziranga Fringe Villages",
    "state": "Assam",
    "district": "Golaghat",
    "tree_count": 890,
    "species": [
      "Simul",
      "Hollock"
    ],
    "reason_category": "illegal",
    "reason_detail": "Unauthorized tree felling near national park buffer",
    "project_name": "Unknown commercial logging",
    "authority": "Unknown",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": "NGT/2024/000201",
    "source_url": "https://www.google.com/search?q=Kaziranga%20Fringe%20Villages%20Unknown%20commercial%20logging%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000009",
    "created_at": "2025-11-14T08:29:10.268Z",
    "lat": 17.312,
    "lng": 78.412,
    "location_name": "Pillar 41 Heritage Banyan (Chevron)",
    "state": "Telangana",
    "district": "Ranga Reddy",
    "tree_count": 1,
    "species": [
      "Heritage Banyan (400+ years)"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Centuries-old heritage banyan threatened for highway expansion; citizen monument tree",
    "project_name": "NH-163 Widening",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": "NGT/2023/000412",
    "source_url": "https://www.google.com/search?q=Pillar%2041%20Heritage%20Banyan%20(Chevron)%20NH-163%20Widening%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000010",
    "created_at": "2026-01-03T08:29:10.268Z",
    "lat": 12.976,
    "lng": 77.592,
    "location_name": "Cubbon Park Heritage Avenue",
    "state": "Karnataka",
    "district": "Bengaluru Urban",
    "tree_count": 47,
    "species": [
      "Rain Tree",
      "Gulmohar",
      "Heritage avenue trees"
    ],
    "reason_category": "metro_rail",
    "reason_detail": "Heritage avenue trees removed for underground metro alignment near park",
    "project_name": "Bengaluru Metro Blue Line",
    "authority": "BMRCL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Cubbon%20Park%20Heritage%20Avenue%20Bengaluru%20Metro%20Blue%20Line%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000011",
    "created_at": "2024-03-24T08:29:10.268Z",
    "lat": 25.435,
    "lng": 81.883,
    "location_name": "Akshayvat Sacred Fig (Prayagraj)",
    "state": "Uttar Pradesh",
    "district": "Prayagraj",
    "tree_count": 1,
    "species": [
      "Sacred Peepal (Akshayvat)"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Ancient sacred fig tree damaged during corridor landscaping works",
    "project_name": "Kumbh Mela Infrastructure",
    "authority": "UP Govt",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Akshayvat%20Sacred%20Fig%20(Prayagraj)%20Kumbh%20Mela%20Infrastructure%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000012",
    "created_at": "2026-02-02T08:29:10.268Z",
    "lat": 22.576,
    "lng": 88.365,
    "location_name": "College Street Heritage Banyan",
    "state": "West Bengal",
    "district": "Kolkata",
    "tree_count": 3,
    "species": [
      "Heritage Banyan",
      "Peepal"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Colonial-era avenue trees felled for tram corridor upgrade",
    "project_name": "Kolkata Tram Corridor",
    "authority": "Kolkata Municipal Corporation",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=College%20Street%20Heritage%20Banyan%20Kolkata%20Tram%20Corridor%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000013",
    "created_at": "2025-04-28T08:29:10.268Z",
    "lat": 31.62,
    "lng": 74.876,
    "location_name": "Dukh Bhanjani Beri (Golden Temple)",
    "state": "Punjab",
    "district": "Amritsar",
    "tree_count": 1,
    "species": [
      "Sacred Ber (heritage)"
    ],
    "reason_category": "disaster_clearance",
    "reason_detail": "Historic ber tree pruned/removed citing safety during plaza redevelopment",
    "project_name": "Heritage Streetscape Amritsar",
    "authority": "SGPC / MC Amritsar",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Dukh%20Bhanjani%20Beri%20(Golden%20Temple)%20Heritage%20Streetscape%20Amritsar%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000014",
    "created_at": "2024-10-10T08:29:10.268Z",
    "lat": 14.02,
    "lng": 77.58,
    "location_name": "Thimmamma Marrimanu Grove Vicinity",
    "state": "Andhra Pradesh",
    "district": "Anantapur",
    "tree_count": 12,
    "species": [
      "Banyan grove",
      "Neem"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees near world's largest banyan canopy cleared for highway realignment",
    "project_name": "NH-40 Expansion",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": "NGT/2022/000178",
    "source_url": "https://www.google.com/search?q=Thimmamma%20Marrimanu%20Grove%20Vicinity%20NH-40%20Expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000015",
    "created_at": "2025-10-25T08:29:10.268Z",
    "lat": 12.272,
    "lng": 76.682,
    "location_name": "Chamundi Hill Sacred Grove",
    "state": "Karnataka",
    "district": "Mysuru",
    "tree_count": 28,
    "species": [
      "Sacred fig",
      "Neem",
      "Sandalwood"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Heritage trees on pilgrimage hill slope cleared for viewing deck",
    "project_name": "Chamundi Tourism Circuit",
    "authority": "Karnataka Tourism",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Chamundi%20Hill%20Sacred%20Grove%20Chamundi%20Tourism%20Circuit%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000016",
    "created_at": "2025-08-06T08:29:10.268Z",
    "lat": 34.084,
    "lng": 74.797,
    "location_name": "Srinagar Boulevard Chinar Row",
    "state": "Jammu and Kashmir",
    "district": "Srinagar",
    "tree_count": 145,
    "species": [
      "Heritage Chinar"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Historic Chinar trees removed or heavily pruned for smart city road widening",
    "project_name": "Srinagar Smart City Roads",
    "authority": "SMC Srinagar",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Srinagar%20Boulevard%20Chinar%20Row%20Srinagar%20Smart%20City%20Roads%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000017",
    "created_at": "2026-02-27T08:29:10.268Z",
    "lat": 18.5,
    "lng": 73.895,
    "location_name": "Empress Garden Heritage Teak",
    "state": "Maharashtra",
    "district": "Pune",
    "tree_count": 19,
    "species": [
      "Heritage Teak",
      "Rain Tree"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Colonial-era garden trees felled for adjacent commercial tower compound",
    "project_name": "Camp Area Redevelopment",
    "authority": "PMC Pune",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Empress%20Garden%20Heritage%20Teak%20Camp%20Area%20Redevelopment%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000018",
    "created_at": "2025-03-09T08:29:10.268Z",
    "lat": 23.022,
    "lng": 72.587,
    "location_name": "Manek Chowk Heritage Peepal",
    "state": "Gujarat",
    "district": "Ahmedabad",
    "tree_count": 2,
    "species": [
      "Heritage Peepal"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Old city heritage peepal removed for pedestrian plaza stone paving",
    "project_name": "Heritage City Square",
    "authority": "AMC Ahmedabad",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Manek%20Chowk%20Heritage%20Peepal%20Heritage%20City%20Square%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000019",
    "created_at": "2025-12-04T08:29:10.268Z",
    "lat": 12.991,
    "lng": 80.233,
    "location_name": "IIT Madras Heritage Banyan Cluster",
    "state": "Tamil Nadu",
    "district": "Chennai",
    "tree_count": 8,
    "species": [
      "Heritage Banyan"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Campus heritage banyans cut for underground cable corridor",
    "project_name": "Campus Power Upgrade",
    "authority": "IIT Madras / TNEB",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=IIT%20Madras%20Heritage%20Banyan%20Cluster%20Campus%20Power%20Upgrade%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000020",
    "created_at": "2024-07-02T08:29:10.268Z",
    "lat": 26.23,
    "lng": 78.182,
    "location_name": "Gwalior Fort Sacred Peepal",
    "state": "Madhya Pradesh",
    "district": "Gwalior",
    "tree_count": 1,
    "species": [
      "Sacred Peepal (fort heritage)"
    ],
    "reason_category": "disaster_clearance",
    "reason_detail": "Monument-zone heritage tree felled citing fort wall stabilization",
    "project_name": "ASI Fort Conservation",
    "authority": "ASI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Gwalior%20Fort%20Sacred%20Peepal%20ASI%20Fort%20Conservation%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000021",
    "created_at": "2025-12-24T08:29:10.268Z",
    "lat": 26.85,
    "lng": 80.946,
    "location_name": "Lucknow Residency Heritage Gulmohar",
    "state": "Uttar Pradesh",
    "district": "Lucknow",
    "tree_count": 14,
    "species": [
      "Heritage Gulmohar",
      "Ashoka"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Colonial Residency heritage trees removed for LED streetscape",
    "project_name": "Smart Lucknow Lighting",
    "authority": "Lucknow Smart City",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Lucknow%20Residency%20Heritage%20Gulmohar%20Smart%20Lucknow%20Lighting%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000022",
    "created_at": "2026-01-23T08:29:10.268Z",
    "lat": 24.572,
    "lng": 73.683,
    "location_name": "Udaipur Lake Pichola Heritage Trees",
    "state": "Rajasthan",
    "district": "Udaipur",
    "tree_count": 22,
    "species": [
      "Heritage Peepal",
      "Khejri"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Lakeside heritage trees cleared for promenade and hotel setback",
    "project_name": "Lakefront Beautification",
    "authority": "UIT Udaipur",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Udaipur%20Lake%20Pichola%20Heritage%20Trees%20Lakefront%20Beautification%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000023",
    "created_at": "2025-10-05T08:29:10.268Z",
    "lat": 30.316,
    "lng": 78.032,
    "location_name": "Dehradun Sal Heritage Corridor",
    "state": "Uttarakhand",
    "district": "Dehradun",
    "tree_count": 67,
    "species": [
      "Heritage Sal",
      "Deodar"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Pre-independence sal avenue trees felled for highway expansion",
    "project_name": "Dehradun-Mussoorie Road",
    "authority": "PWD Uttarakhand",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": "NGT/2023/000567",
    "source_url": "https://www.google.com/search?q=Dehradun%20Sal%20Heritage%20Corridor%20Dehradun-Mussoorie%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000024",
    "created_at": "2025-06-17T08:29:10.268Z",
    "lat": 13.628,
    "lng": 79.419,
    "location_name": "Tirupati Temple Heritage Avenue",
    "state": "Andhra Pradesh",
    "district": "Tirupati",
    "tree_count": 35,
    "species": [
      "Neem",
      "Peepal (temple heritage)"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Pilgrimage route heritage trees removed for queue complex expansion",
    "project_name": "Tirupati Queue Complex",
    "authority": "TTD",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Tirupati%20Temple%20Heritage%20Avenue%20Tirupati%20Queue%20Complex%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000025",
    "created_at": "2025-11-14T08:29:10.268Z",
    "lat": 25.578,
    "lng": 91.893,
    "location_name": "Shillong Ward's Lake Heritage Oaks",
    "state": "Meghalaya",
    "district": "East Khasi Hills",
    "tree_count": 11,
    "species": [
      "Heritage Oak",
      "Rhododendron"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Colonial-era lake fringe trees cut for concrete embankment",
    "project_name": "Ward's Lake Revamp",
    "authority": "Shillong Municipal Board",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Shillong%20Ward's%20Lake%20Heritage%20Oaks%20Ward's%20Lake%20Revamp%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000026",
    "created_at": "2026-02-12T08:29:10.268Z",
    "lat": 20.244,
    "lng": 85.834,
    "location_name": "Bhubaneswar Ekamra Heritage Grove",
    "state": "Odisha",
    "district": "Khordha",
    "tree_count": 41,
    "species": [
      "Sacred fig",
      "Banyan (Ekamra heritage)"
    ],
    "reason_category": "metro_rail",
    "reason_detail": "Heritage grove trees cleared for metro depot near temple precinct",
    "project_name": "Bhubaneswar Metro",
    "authority": "Odisha Metro",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": "NGT/2024/000334",
    "source_url": "https://www.google.com/search?q=Bhubaneswar%20Ekamra%20Heritage%20Grove%20Bhubaneswar%20Metro%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000027",
    "created_at": "2023-12-15T08:29:10.268Z",
    "lat": 21.146,
    "lng": 79.088,
    "location_name": "Nagpur Zero Mile Heritage Banyan",
    "state": "Maharashtra",
    "district": "Nagpur",
    "tree_count": 1,
    "species": [
      "Heritage Banyan (city marker)"
    ],
    "reason_category": "metro_rail",
    "reason_detail": "City-centre heritage banyan transplanted/felled for metro station box",
    "project_name": "Nagpur Metro",
    "authority": "Maha Metro",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Nagpur%20Zero%20Mile%20Heritage%20Banyan%20Nagpur%20Metro%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000028",
    "created_at": "2026-01-13T08:29:10.268Z",
    "lat": 9.931,
    "lng": 76.267,
    "location_name": "Kochi Marine Drive Heritage Rain Trees",
    "state": "Kerala",
    "district": "Ernakulam",
    "tree_count": 24,
    "species": [
      "Heritage Rain Tree"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Waterfront heritage rain trees removed for promenade widening",
    "project_name": "Marine Drive Upgrade",
    "authority": "Kochi Corporation",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kochi%20Marine%20Drive%20Heritage%20Rain%20Trees%20Marine%20Drive%20Upgrade%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000029",
    "created_at": "2024-10-10T08:29:10.268Z",
    "lat": 26.9124,
    "lng": 75.7873,
    "location_name": "Nahargarh Hills",
    "state": "Rajasthan",
    "district": "Jaipur",
    "tree_count": 234,
    "species": [
      "Khejri",
      "Neem"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Jaipur Ring Road Phase 3 in Nahargarh Hills",
    "project_name": "Jaipur Ring Road Phase 3",
    "authority": "PWD Rajasthan",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Nahargarh%20Hills%20Jaipur%20Ring%20Road%20Phase%203%20India%20trees%20news&hl=en-IN",
    "source_type": "scraped",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000030",
    "created_at": "2025-08-16T08:29:10.268Z",
    "lat": 11.0168,
    "lng": 76.9558,
    "location_name": "Coimbatore Western Ghats Foothills",
    "state": "Tamil Nadu",
    "district": "Coimbatore",
    "tree_count": 678,
    "species": [
      "Rosewood",
      "Teak"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Trees felled or cleared for TN Power Grid Upgrade in Coimbatore Western Ghats Foothills",
    "project_name": "TN Power Grid Upgrade",
    "authority": "TANGEDCO",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Coimbatore%20Western%20Ghats%20Foothills%20TN%20Power%20Grid%20Upgrade%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000031",
    "created_at": "2025-12-14T08:29:10.268Z",
    "lat": 22.5726,
    "lng": 88.3639,
    "location_name": "East Kolkata Wetlands Fringe",
    "state": "West Bengal",
    "district": "Kolkata",
    "tree_count": 320,
    "species": [
      "Mangrove",
      "Sundari"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for New Town IT Hub Extension in East Kolkata Wetlands Fringe",
    "project_name": "New Town IT Hub Extension",
    "authority": "WBHIDCO",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": "NGT/2023/000112",
    "source_url": "https://www.google.com/search?q=East%20Kolkata%20Wetlands%20Fringe%20New%20Town%20IT%20Hub%20Extension%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000032",
    "created_at": "2025-03-09T08:29:10.268Z",
    "lat": 30.7333,
    "lng": 76.7794,
    "location_name": "Sukhna Lake Catchment",
    "state": "Chandigarh",
    "district": "Chandigarh",
    "tree_count": 89,
    "species": [
      "Eucalyptus",
      "Shisham"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Trees felled or cleared for Sukhna Lake Revitalization in Sukhna Lake Catchment",
    "project_name": "Sukhna Lake Revitalization",
    "authority": "Chandigarh Administration",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Sukhna%20Lake%20Catchment%20Sukhna%20Lake%20Revitalization%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000033",
    "created_at": "2025-11-04T08:29:10.268Z",
    "lat": 26.8467,
    "lng": 80.9462,
    "location_name": "Lucknow-Kanpur Expressway Stretch",
    "state": "Uttar Pradesh",
    "district": "Lucknow",
    "tree_count": 1240,
    "species": [
      "Neem",
      "Peepal"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Lucknow-Kanpur Expressway in Lucknow-Kanpur Expressway Stretch",
    "project_name": "Lucknow-Kanpur Expressway",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Lucknow-Kanpur%20Expressway%20Stretch%20Lucknow-Kanpur%20Expressway%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000034",
    "created_at": "2025-09-05T08:29:10.268Z",
    "lat": 21.1702,
    "lng": 72.8311,
    "location_name": "Surat Dumas Road",
    "state": "Gujarat",
    "district": "Surat",
    "tree_count": 445,
    "species": [
      "Mango",
      "Gulmohar"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Surat Coastal Road in Surat Dumas Road",
    "project_name": "Surat Coastal Road",
    "authority": "Surat Municipal Corporation",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Surat%20Dumas%20Road%20Surat%20Coastal%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "scraped",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000035",
    "created_at": "2025-02-07T08:29:10.268Z",
    "lat": 25.5941,
    "lng": 85.1376,
    "location_name": "Patna Ganga Embankment",
    "state": "Bihar",
    "district": "Patna",
    "tree_count": 178,
    "species": [
      "Banyan",
      "Peepal"
    ],
    "reason_category": "disaster_clearance",
    "reason_detail": "Trees felled or cleared for Ganga Embankment Reinforcement in Patna Ganga Embankment",
    "project_name": "Ganga Embankment Reinforcement",
    "authority": "Water Resources Dept Bihar",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Patna%20Ganga%20Embankment%20Ganga%20Embankment%20Reinforcement%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000036",
    "created_at": "2026-03-14T08:29:10.268Z",
    "lat": 31.1048,
    "lng": 77.1734,
    "location_name": "Shimla Ridge Forest",
    "state": "Himachal Pradesh",
    "district": "Shimla",
    "tree_count": 567,
    "species": [
      "Deodar",
      "Oak"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Shimla Bypass Road in Shimla Ridge Forest",
    "project_name": "Shimla Bypass Road",
    "authority": "PWD Himachal",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": "NGT/2024/000078",
    "source_url": "https://www.google.com/search?q=Shimla%20Ridge%20Forest%20Shimla%20Bypass%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000037",
    "created_at": "2025-11-14T08:29:10.268Z",
    "lat": 9.9312,
    "lng": 76.2673,
    "location_name": "Kochi Metro Extension",
    "state": "Kerala",
    "district": "Ernakulam",
    "tree_count": 312,
    "species": [
      "Coconut",
      "Jackfruit"
    ],
    "reason_category": "metro_rail",
    "reason_detail": "Trees felled or cleared for Kochi Metro Phase II in Kochi Metro Extension",
    "project_name": "Kochi Metro Phase II",
    "authority": "KMRL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kochi%20Metro%20Extension%20Kochi%20Metro%20Phase%20II%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000038",
    "created_at": "2024-11-29T08:29:10.268Z",
    "lat": 27.1767,
    "lng": 78.0081,
    "location_name": "Agra Yamuna Expressway Greenbelt",
    "state": "Uttar Pradesh",
    "district": "Agra",
    "tree_count": 2100,
    "species": [
      "Neem",
      "Keekar"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Yamuna Expressway Phase 2 in Agra Yamuna Expressway Greenbelt",
    "project_name": "Yamuna Expressway Phase 2",
    "authority": "YEIDA",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Agra%20Yamuna%20Expressway%20Greenbelt%20Yamuna%20Expressway%20Phase%202%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000039",
    "created_at": "2025-05-18T08:29:10.268Z",
    "lat": 18.5204,
    "lng": 73.8567,
    "location_name": "Pune-Mumbai Expressway Hill Section",
    "state": "Maharashtra",
    "district": "Pune",
    "tree_count": 734,
    "species": [
      "Teak",
      "Bamboo"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Mumbai-Pune Expressway Widening in Pune-Mumbai Expressway Hill Section",
    "project_name": "Mumbai-Pune Expressway Widening",
    "authority": "MSRDC",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Pune-Mumbai%20Expressway%20Hill%20Section%20Mumbai-Pune%20Expressway%20Widening%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000040",
    "created_at": "2026-04-03T08:29:10.268Z",
    "lat": 13.0827,
    "lng": 80.2707,
    "location_name": "Chennai IT Corridor (OMR)",
    "state": "Tamil Nadu",
    "district": "Chennai",
    "tree_count": 98,
    "species": [
      "Rain Tree",
      "Gulmohar"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for OMR IT Park Phase 4 in Chennai IT Corridor (OMR)",
    "project_name": "OMR IT Park Phase 4",
    "authority": "CMDA",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Chennai%20IT%20Corridor%20(OMR)%20OMR%20IT%20Park%20Phase%204%20India%20trees%20news&hl=en-IN",
    "source_type": "scraped",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000041",
    "created_at": "2026-02-22T08:29:10.268Z",
    "lat": 23.3441,
    "lng": 85.3096,
    "location_name": "Ranchi HEC Sector",
    "state": "Jharkhand",
    "district": "Ranchi",
    "tree_count": 56,
    "species": [
      "Sal",
      "Mahua"
    ],
    "reason_category": "illegal",
    "reason_detail": "Trees felled or cleared for HEC Colony Expansion in Ranchi HEC Sector",
    "project_name": "HEC Colony Expansion",
    "authority": "Private developers",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Ranchi%20HEC%20Sector%20HEC%20Colony%20Expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000042",
    "created_at": "2023-12-15T08:29:10.268Z",
    "lat": 25.3176,
    "lng": 82.9739,
    "location_name": "Varanasi Kashi Corridor",
    "state": "Uttar Pradesh",
    "district": "Varanasi",
    "tree_count": 67,
    "species": [
      "Peepal",
      "Banyan"
    ],
    "reason_category": "disaster_clearance",
    "reason_detail": "Trees felled or cleared for Kashi Vishwanath Corridor in Varanasi Kashi Corridor",
    "project_name": "Kashi Vishwanath Corridor",
    "authority": "UP Govt",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Varanasi%20Kashi%20Corridor%20Kashi%20Vishwanath%20Corridor%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000043",
    "created_at": "2025-07-17T08:29:10.268Z",
    "lat": 11.9416,
    "lng": 79.8083,
    "location_name": "Puducherry Coastal Road",
    "state": "Puducherry",
    "district": "Puducherry",
    "tree_count": 34,
    "species": [
      "Casuarina",
      "Coconut"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Puducherry Coastal Road in Puducherry Coastal Road",
    "project_name": "Puducherry Coastal Road",
    "authority": "PWD Puducherry",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Puducherry%20Coastal%20Road%20Puducherry%20Coastal%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "scraped",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000044",
    "created_at": "2025-11-24T08:29:10.268Z",
    "lat": 27.3389,
    "lng": 88.6065,
    "location_name": "Gangtok NH-10 Corridor",
    "state": "Sikkim",
    "district": "East Sikkim",
    "tree_count": 423,
    "species": [
      "Rhododendron",
      "Oak"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for NH-10 Gangtok Section in Gangtok NH-10 Corridor",
    "project_name": "NH-10 Gangtok Section",
    "authority": "NHIDCL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": "NGT/2023/000890",
    "source_url": "https://www.google.com/search?q=Gangtok%20NH-10%20Corridor%20NH-10%20Gangtok%20Section%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000045",
    "created_at": "2026-01-13T08:29:10.268Z",
    "lat": 18.327,
    "lng": 82.877,
    "location_name": "Araku Valley Coffee Forest",
    "state": "Andhra Pradesh",
    "district": "Alluri Sitharama Raju",
    "tree_count": 1200,
    "species": [
      "Coffee shade trees",
      "Teak"
    ],
    "reason_category": "mining",
    "reason_detail": "Forest patches cleared for bauxite corridor access roads",
    "project_name": "Araku Mining Access Roads",
    "authority": "AP Mineral Development",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Araku%20Valley%20Coffee%20Forest%20Araku%20Mining%20Access%20Roads%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000046",
    "created_at": "2025-10-25T08:29:10.268Z",
    "lat": 17.686,
    "lng": 83.218,
    "location_name": "Vizag Steel Plant Greenbelt",
    "state": "Andhra Pradesh",
    "district": "Visakhapatnam",
    "tree_count": 340,
    "species": [
      "Casuarina",
      "Eucalyptus"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for Vizag Industrial Corridor in Vizag Steel Plant Greenbelt",
    "project_name": "Vizag Industrial Corridor",
    "authority": "RINL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Vizag%20Steel%20Plant%20Greenbelt%20Vizag%20Industrial%20Corridor%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000047",
    "created_at": "2025-08-06T08:29:10.268Z",
    "lat": 27.084,
    "lng": 93.605,
    "location_name": "Itanagar Papum Reserve Fringe",
    "state": "Arunachal Pradesh",
    "district": "Papum Pare",
    "tree_count": 2100,
    "species": [
      "Hollock",
      "Bamboo"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Itanagar Highway in Itanagar Papum Reserve Fringe",
    "project_name": "Itanagar Highway",
    "authority": "MoRTH",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Itanagar%20Papum%20Reserve%20Fringe%20Itanagar%20Highway%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000048",
    "created_at": "2024-03-24T08:29:10.268Z",
    "lat": 28.125,
    "lng": 95.768,
    "location_name": "Dibang Valley Hydel Site",
    "state": "Arunachal Pradesh",
    "district": "Dibang Valley",
    "tree_count": 270000,
    "species": [
      "Subtropical evergreen"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Mass forest submergence for hydropower reservoir",
    "project_name": "Etalin Hydroelectric Project",
    "authority": "NHPC / JV",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": "NGT/2020/000778",
    "source_url": "https://www.google.com/search?q=Dibang%20Valley%20Hydel%20Site%20Etalin%20Hydroelectric%20Project%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000049",
    "created_at": "2026-02-02T08:29:10.268Z",
    "lat": 23.12,
    "lng": 82.95,
    "location_name": "Hasdeo Arand Coal Blocks",
    "state": "Chhattisgarh",
    "district": "Surguja",
    "tree_count": 250000,
    "species": [
      "Sal",
      "Teak",
      "Mahua"
    ],
    "reason_category": "mining",
    "reason_detail": "Dense forest diversion for coal mining in Hasdeo Arand",
    "project_name": "Parsa East & Kete Basan Coal",
    "authority": "Coal India / Adani",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": "NGT/2024/000445",
    "source_url": "https://www.google.com/search?q=Hasdeo%20Arand%20Coal%20Blocks%20Parsa%20East%20%26%20Kete%20Basan%20Coal%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000050",
    "created_at": "2025-04-28T08:29:10.268Z",
    "lat": 19.1,
    "lng": 81.95,
    "location_name": "Bastar Iron Ore Corridor",
    "state": "Chhattisgarh",
    "district": "Bastar",
    "tree_count": 8900,
    "species": [
      "Sal",
      "Bamboo"
    ],
    "reason_category": "mining",
    "reason_detail": "Trees felled or cleared for Bailadila Iron Ore Expansion in Bastar Iron Ore Corridor",
    "project_name": "Bailadila Iron Ore Expansion",
    "authority": "NMDC",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Bastar%20Iron%20Ore%20Corridor%20Bailadila%20Iron%20Ore%20Expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000051",
    "created_at": "2025-12-04T08:29:10.268Z",
    "lat": 28.408,
    "lng": 77.086,
    "location_name": "Gurugram Aravalli Foothills",
    "state": "Haryana",
    "district": "Gurugram",
    "tree_count": 412,
    "species": [
      "Dhau",
      "Khejri"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for Dwarka Expressway in Gurugram Aravalli Foothills",
    "project_name": "Dwarka Expressway",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": "NGT/2023/000289",
    "source_url": "https://www.google.com/search?q=Gurugram%20Aravalli%20Foothills%20Dwarka%20Expressway%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000052",
    "created_at": "2026-04-18T08:29:10.268Z",
    "lat": 30.45,
    "lng": 77.62,
    "location_name": "Kalesar National Park Buffer",
    "state": "Haryana",
    "district": "Yamunanagar",
    "tree_count": 156,
    "species": [
      "Sal",
      "Shisham"
    ],
    "reason_category": "illegal",
    "reason_detail": "Trees felled or cleared for Unauthorized quarry access in Kalesar National Park Buffer",
    "project_name": "Unauthorized quarry access",
    "authority": "Unknown",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kalesar%20National%20Park%20Buffer%20Unauthorized%20quarry%20access%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000053",
    "created_at": "2025-09-25T08:29:10.268Z",
    "lat": 24.56,
    "lng": 93.77,
    "location_name": "Imphal Loktak Wetland Fringe",
    "state": "Manipur",
    "district": "Bishnupur",
    "tree_count": 230,
    "species": [
      "Phumdi vegetation",
      "Willow"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Trees felled or cleared for Loktak Downstream Project in Imphal Loktak Wetland Fringe",
    "project_name": "Loktak Downstream Project",
    "authority": "NHPC",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Imphal%20Loktak%20Wetland%20Fringe%20Loktak%20Downstream%20Project%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000054",
    "created_at": "2026-03-24T08:29:10.268Z",
    "lat": 24.33,
    "lng": 93.68,
    "location_name": "Churachandpur Hill Forest",
    "state": "Manipur",
    "district": "Churachandpur",
    "tree_count": 890,
    "species": [
      "Oak",
      "Pine"
    ],
    "reason_category": "illegal",
    "reason_detail": "Trees felled or cleared for Hill road expansion logging in Churachandpur Hill Forest",
    "project_name": "Hill road expansion logging",
    "authority": "Local contractors",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Churachandpur%20Hill%20Forest%20Hill%20road%20expansion%20logging%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000055",
    "created_at": "2025-01-18T08:29:10.268Z",
    "lat": 25.52,
    "lng": 90.22,
    "location_name": "Garo Hills Coal Belt",
    "state": "Meghalaya",
    "district": "West Garo Hills",
    "tree_count": 3400,
    "species": [
      "Subtropical broadleaf"
    ],
    "reason_category": "mining",
    "reason_detail": "Trees felled or cleared for Rat-hole mining expansion in Garo Hills Coal Belt",
    "project_name": "Rat-hole mining expansion",
    "authority": "Private miners",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Garo%20Hills%20Coal%20Belt%20Rat-hole%20mining%20expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000056",
    "created_at": "2025-12-24T08:29:10.268Z",
    "lat": 25.45,
    "lng": 91.78,
    "location_name": "Mawphlang Sacred Grove Vicinity",
    "state": "Meghalaya",
    "district": "East Khasi Hills",
    "tree_count": 18,
    "species": [
      "Sacred grove trees"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees adjacent to UNESCO-nominated sacred grove cleared for road",
    "project_name": "Shillong-Dawki Road",
    "authority": "PWD Meghalaya",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Mawphlang%20Sacred%20Grove%20Vicinity%20Shillong-Dawki%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000057",
    "created_at": "2026-03-04T08:29:10.268Z",
    "lat": 23.55,
    "lng": 92.35,
    "location_name": "Dampa Tiger Reserve Fringe",
    "state": "Mizoram",
    "district": "Mamit",
    "tree_count": 670,
    "species": [
      "Tropical evergreen"
    ],
    "reason_category": "illegal",
    "reason_detail": "Trees felled or cleared for Jhum expansion logging in Dampa Tiger Reserve Fringe",
    "project_name": "Jhum expansion logging",
    "authority": "Unknown",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Dampa%20Tiger%20Reserve%20Fringe%20Jhum%20expansion%20logging%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000058",
    "created_at": "2025-11-14T08:29:10.268Z",
    "lat": 25.55,
    "lng": 94.12,
    "location_name": "Kohima Dzukou Foothills",
    "state": "Nagaland",
    "district": "Kohima",
    "tree_count": 445,
    "species": [
      "Rhododendron",
      "Oak"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Kohima-Dzukou Tourism Road in Kohima Dzukou Foothills",
    "project_name": "Kohima-Dzukou Tourism Road",
    "authority": "PWD Nagaland",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kohima%20Dzukou%20Foothills%20Kohima-Dzukou%20Tourism%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "scraped",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000059",
    "created_at": "2025-06-17T08:29:10.268Z",
    "lat": 21.72,
    "lng": 86.42,
    "location_name": "Simlipal Biosphere Fringe",
    "state": "Odisha",
    "district": "Mayurbhanj",
    "tree_count": 1560,
    "species": [
      "Sal",
      "Mahua"
    ],
    "reason_category": "mining",
    "reason_detail": "Trees felled or cleared for Iron ore corridor in Simlipal Biosphere Fringe",
    "project_name": "Iron ore corridor",
    "authority": "Odisha Mining",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Simlipal%20Biosphere%20Fringe%20Iron%20ore%20corridor%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000060",
    "created_at": "2026-01-23T08:29:10.268Z",
    "lat": 19.82,
    "lng": 86.1,
    "location_name": "Puri Konark Coastal Forest",
    "state": "Odisha",
    "district": "Puri",
    "tree_count": 89,
    "species": [
      "Casuarina",
      "Coconut"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Puri-Konark Marine Drive in Puri Konark Coastal Forest",
    "project_name": "Puri-Konark Marine Drive",
    "authority": "Odisha PWD",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Puri%20Konark%20Coastal%20Forest%20Puri-Konark%20Marine%20Drive%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000061",
    "created_at": "2025-08-26T08:29:10.268Z",
    "lat": 30.9,
    "lng": 75.85,
    "location_name": "Ludhiana Bypass Greenbelt",
    "state": "Punjab",
    "district": "Ludhiana",
    "tree_count": 520,
    "species": [
      "Eucalyptus",
      "Poplar"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Ludhiana Ring Road in Ludhiana Bypass Greenbelt",
    "project_name": "Ludhiana Ring Road",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Ludhiana%20Bypass%20Greenbelt%20Ludhiana%20Ring%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000062",
    "created_at": "2026-02-12T08:29:10.268Z",
    "lat": 31.02,
    "lng": 76.52,
    "location_name": "Ropar Wetland Fringe",
    "state": "Punjab",
    "district": "Rupnagar",
    "tree_count": 78,
    "species": [
      "Shisham",
      "Kikar"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Trees felled or cleared for Sutlej embankment works in Ropar Wetland Fringe",
    "project_name": "Sutlej embankment works",
    "authority": "Punjab WRD",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Ropar%20Wetland%20Fringe%20Sutlej%20embankment%20works%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000063",
    "created_at": "2025-11-24T08:29:10.268Z",
    "lat": 23.68,
    "lng": 91.32,
    "location_name": "Agartala Sepahijala Fringe",
    "state": "Tripura",
    "district": "Sepahijala",
    "tree_count": 340,
    "species": [
      "Sal",
      "Bamboo"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Agartala Bypass in Agartala Sepahijala Fringe",
    "project_name": "Agartala Bypass",
    "authority": "MoRTH",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Agartala%20Sepahijala%20Fringe%20Agartala%20Bypass%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000064",
    "created_at": "2026-03-19T08:29:10.268Z",
    "lat": 29.53,
    "lng": 78.77,
    "location_name": "Jim Corbett Buffer Zone",
    "state": "Uttarakhand",
    "district": "Nainital",
    "tree_count": 234,
    "species": [
      "Sal",
      "Sheesham"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for Resort corridor expansion in Jim Corbett Buffer Zone",
    "project_name": "Resort corridor expansion",
    "authority": "Private developers",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": "NGT/2024/000112",
    "source_url": "https://www.google.com/search?q=Jim%20Corbett%20Buffer%20Zone%20Resort%20corridor%20expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000065",
    "created_at": "2024-10-10T08:29:10.268Z",
    "lat": 30.38,
    "lng": 78.48,
    "location_name": "Tehri Dam Catchment",
    "state": "Uttarakhand",
    "district": "Tehri Garhwal",
    "tree_count": 12000,
    "species": [
      "Deodar",
      "Oak"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Trees felled or cleared for Tehri Pumped Storage in Tehri Dam Catchment",
    "project_name": "Tehri Pumped Storage",
    "authority": "THDC",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Tehri%20Dam%20Catchment%20Tehri%20Pumped%20Storage%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000066",
    "created_at": "2025-10-25T08:29:10.268Z",
    "lat": 21.95,
    "lng": 88.9,
    "location_name": "Sundarbans Mangrove Fringe",
    "state": "West Bengal",
    "district": "South 24 Parganas",
    "tree_count": 4500,
    "species": [
      "Sundari",
      "Gewa"
    ],
    "reason_category": "disaster_clearance",
    "reason_detail": "Trees felled or cleared for Embankment reinforcement in Sundarbans Mangrove Fringe",
    "project_name": "Embankment reinforcement",
    "authority": "Irrigation Dept WB",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Sundarbans%20Mangrove%20Fringe%20Embankment%20reinforcement%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000067",
    "created_at": "2025-08-06T08:29:10.268Z",
    "lat": 27.04,
    "lng": 88.26,
    "location_name": "Darjeeling Tea Estate Forest",
    "state": "West Bengal",
    "district": "Darjeeling",
    "tree_count": 167,
    "species": [
      "Oak",
      "Rhododendron"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Hill cart road widening in Darjeeling Tea Estate Forest",
    "project_name": "Hill cart road widening",
    "authority": "PWD WB",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Darjeeling%20Tea%20Estate%20Forest%20Hill%20cart%20road%20widening%20India%20trees%20news&hl=en-IN",
    "source_type": "scraped",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000068",
    "created_at": "2025-12-04T08:29:10.268Z",
    "lat": 11.62,
    "lng": 92.72,
    "location_name": "Port Blair Mangrove Belt",
    "state": "Andaman and Nicobar Islands",
    "district": "South Andaman",
    "tree_count": 890,
    "species": [
      "Mangrove",
      "Beach almond"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for Coastal tourism infrastructure in Port Blair Mangrove Belt",
    "project_name": "Coastal tourism infrastructure",
    "authority": "ANI Administration",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Port%20Blair%20Mangrove%20Belt%20Coastal%20tourism%20infrastructure%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000069",
    "created_at": "2025-04-28T08:29:10.268Z",
    "lat": 20.27,
    "lng": 73.02,
    "location_name": "Silvassa Industrial Estate",
    "state": "Dadra and Nagar Haveli and Daman and Diu",
    "district": "Dadra and Nagar Haveli",
    "tree_count": 234,
    "species": [
      "Teak",
      "Bamboo"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for Industrial plot expansion in Silvassa Industrial Estate",
    "project_name": "Industrial plot expansion",
    "authority": "UT Administration",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Silvassa%20Industrial%20Estate%20Industrial%20plot%20expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "scraped",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000070",
    "created_at": "2026-01-03T08:29:10.268Z",
    "lat": 34.15,
    "lng": 77.58,
    "location_name": "Leh Indus Valley Plantation",
    "state": "Ladakh",
    "district": "Leh",
    "tree_count": 45,
    "species": [
      "Poplar",
      "Willow"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Trees felled or cleared for Leh smart city landscaping in Leh Indus Valley Plantation",
    "project_name": "Leh smart city landscaping",
    "authority": "LAHDC Leh",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Leh%20Indus%20Valley%20Plantation%20Leh%20smart%20city%20landscaping%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000071",
    "created_at": "2025-07-17T08:29:10.268Z",
    "lat": 34.55,
    "lng": 76.12,
    "location_name": "Kargil Drass Road Corridor",
    "state": "Ladakh",
    "district": "Kargil",
    "tree_count": 12,
    "species": [
      "Willow",
      "Poplar"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Zoji La tunnel approach in Kargil Drass Road Corridor",
    "project_name": "Zoji La tunnel approach",
    "authority": "NHIDCL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kargil%20Drass%20Road%20Corridor%20Zoji%20La%20tunnel%20approach%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000072",
    "created_at": "2025-01-18T08:29:10.268Z",
    "lat": 10.57,
    "lng": 72.64,
    "location_name": "Kavaratti Coconut Grove",
    "state": "Lakshadweep",
    "district": "Lakshadweep",
    "tree_count": 28,
    "species": [
      "Coconut",
      "Pandanus"
    ],
    "reason_category": "urban_beautification",
    "reason_detail": "Trees felled or cleared for Island airport approach beautification in Kavaratti Coconut Grove",
    "project_name": "Island airport approach beautification",
    "authority": "Lakshadweep Admin",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kavaratti%20Coconut%20Grove%20Island%20airport%20approach%20beautification%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "completed"
  },
  {
    "id": "00000000-0000-0000-0000-000000000073",
    "created_at": "2025-03-09T08:29:10.268Z",
    "lat": 22.75,
    "lng": 77.72,
    "location_name": "Narmada Riverbank Satpura",
    "state": "Madhya Pradesh",
    "district": "Hoshangabad",
    "tree_count": 3400,
    "species": [
      "Teak",
      "Sal"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Trees felled or cleared for Narmada hydel cascade in Narmada Riverbank Satpura",
    "project_name": "Narmada hydel cascade",
    "authority": "MPPGCL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Narmada%20Riverbank%20Satpura%20Narmada%20hydel%20cascade%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000074",
    "created_at": "2025-11-14T08:29:10.268Z",
    "lat": 22.2,
    "lng": 80.6,
    "location_name": "Kanha-Pench Corridor",
    "state": "Madhya Pradesh",
    "district": "Mandla",
    "tree_count": 780,
    "species": [
      "Sal",
      "Bamboo"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Tiger corridor highway in Kanha-Pench Corridor",
    "project_name": "Tiger corridor highway",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": "NGT/2023/000901",
    "source_url": "https://www.google.com/search?q=Kanha-Pench%20Corridor%20Tiger%20corridor%20highway%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000075",
    "created_at": "2025-12-24T08:29:10.268Z",
    "lat": 22.72,
    "lng": 75.86,
    "location_name": "Indore Bypass Aravalli Patch",
    "state": "Madhya Pradesh",
    "district": "Indore",
    "tree_count": 445,
    "species": [
      "Bamboo",
      "Teak"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Indore Ring Road in Indore Bypass Aravalli Patch",
    "project_name": "Indore Ring Road",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Indore%20Bypass%20Aravalli%20Patch%20Indore%20Ring%20Road%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000076",
    "created_at": "2025-04-28T08:29:10.268Z",
    "lat": 18.98,
    "lng": 73.12,
    "location_name": "Navi Mumbai Airport Influence Zone",
    "state": "Maharashtra",
    "district": "Raigad",
    "tree_count": 12000,
    "species": [
      "Mangrove",
      "Casuarina"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for Navi Mumbai International Airport in Navi Mumbai Airport Influence Zone",
    "project_name": "Navi Mumbai International Airport",
    "authority": "CIDCO",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Navi%20Mumbai%20Airport%20Influence%20Zone%20Navi%20Mumbai%20International%20Airport%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000077",
    "created_at": "2026-01-23T08:29:10.268Z",
    "lat": 20.25,
    "lng": 79.35,
    "location_name": "Tadoba Buffer Zone",
    "state": "Maharashtra",
    "district": "Chandrapur",
    "tree_count": 567,
    "species": [
      "Teak",
      "Bamboo"
    ],
    "reason_category": "mining",
    "reason_detail": "Trees felled or cleared for Coal washery expansion in Tadoba Buffer Zone",
    "project_name": "Coal washery expansion",
    "authority": "Western Coalfields",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Tadoba%20Buffer%20Zone%20Coal%20washery%20expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000078",
    "created_at": "2026-04-08T08:29:10.268Z",
    "lat": 26.24,
    "lng": 73.02,
    "location_name": "Jodhpur Aravalli Foothills",
    "state": "Rajasthan",
    "district": "Jodhpur",
    "tree_count": 89,
    "species": [
      "Khejri",
      "Rohida"
    ],
    "reason_category": "mining",
    "reason_detail": "Trees felled or cleared for Sandstone quarry expansion in Jodhpur Aravalli Foothills",
    "project_name": "Sandstone quarry expansion",
    "authority": "Private leaseholders",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Jodhpur%20Aravalli%20Foothills%20Sandstone%20quarry%20expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000079",
    "created_at": "2025-10-05T08:29:10.268Z",
    "lat": 26.02,
    "lng": 76.39,
    "location_name": "Ranthambore Corridor",
    "state": "Rajasthan",
    "district": "Sawai Madhopur",
    "tree_count": 234,
    "species": [
      "Dhok",
      "Babul"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Tourism highway in Ranthambore Corridor",
    "project_name": "Tourism highway",
    "authority": "PWD Rajasthan",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Ranthambore%20Corridor%20Tourism%20highway%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000080",
    "created_at": "2025-12-14T08:29:10.268Z",
    "lat": 17.35,
    "lng": 78.55,
    "location_name": "Hyderabad ORR Phase 2",
    "state": "Telangana",
    "district": "Ranga Reddy",
    "tree_count": 1890,
    "species": [
      "Neem",
      "Banyan"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Outer Ring Road Expansion in Hyderabad ORR Phase 2",
    "project_name": "Outer Ring Road Expansion",
    "authority": "HMDA",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Hyderabad%20ORR%20Phase%202%20Outer%20Ring%20Road%20Expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000081",
    "created_at": "2026-04-23T08:29:10.268Z",
    "lat": 17.97,
    "lng": 79.6,
    "location_name": "Warangal Forest Fringe",
    "state": "Telangana",
    "district": "Warangal",
    "tree_count": 456,
    "species": [
      "Teak",
      "Bamboo"
    ],
    "reason_category": "illegal",
    "reason_detail": "Trees felled or cleared for Unauthorized timber trade in Warangal Forest Fringe",
    "project_name": "Unauthorized timber trade",
    "authority": "Unknown",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Warangal%20Forest%20Fringe%20Unauthorized%20timber%20trade%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000082",
    "created_at": "2025-11-04T08:29:10.268Z",
    "lat": 10.09,
    "lng": 77.06,
    "location_name": "Munnar Cardamom Hills",
    "state": "Kerala",
    "district": "Idukki",
    "tree_count": 890,
    "species": [
      "Shola",
      "Eucalyptus"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Trees felled or cleared for High-voltage line through shola in Munnar Cardamom Hills",
    "project_name": "High-voltage line through shola",
    "authority": "KSEB",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Munnar%20Cardamom%20Hills%20High-voltage%20line%20through%20shola%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000083",
    "created_at": "2026-03-04T08:29:10.268Z",
    "lat": 11.08,
    "lng": 76.45,
    "location_name": "Silent Valley Buffer",
    "state": "Kerala",
    "district": "Palakkad",
    "tree_count": 120,
    "species": [
      "Evergreen shola"
    ],
    "reason_category": "illegal",
    "reason_detail": "Trees felled or cleared for Encroachment clearing in Silent Valley Buffer",
    "project_name": "Encroachment clearing",
    "authority": "Forest Dept Kerala",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Silent%20Valley%20Buffer%20Encroachment%20clearing%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000084",
    "created_at": "2025-08-26T08:29:10.268Z",
    "lat": 32.73,
    "lng": 74.87,
    "location_name": "Jammu Pine Forest Belt",
    "state": "Jammu and Kashmir",
    "district": "Jammu",
    "tree_count": 678,
    "species": [
      "Chir Pine"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Jammu-Udhampur Highway in Jammu Pine Forest Belt",
    "project_name": "Jammu-Udhampur Highway",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Jammu%20Pine%20Forest%20Belt%20Jammu-Udhampur%20Highway%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000085",
    "created_at": "2025-01-18T08:29:10.268Z",
    "lat": 23.8,
    "lng": 86.43,
    "location_name": "Dhanbad Coal Belt",
    "state": "Jharkhand",
    "district": "Dhanbad",
    "tree_count": 8900,
    "species": [
      "Sal",
      "Mahua"
    ],
    "reason_category": "mining",
    "reason_detail": "Trees felled or cleared for BCCL expansion in Dhanbad Coal Belt",
    "project_name": "BCCL expansion",
    "authority": "BCCL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Dhanbad%20Coal%20Belt%20BCCL%20expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000086",
    "created_at": "2026-03-09T08:29:10.268Z",
    "lat": 23.85,
    "lng": 84.1,
    "location_name": "Palamu Tiger Reserve Fringe",
    "state": "Jharkhand",
    "district": "Palamu",
    "tree_count": 445,
    "species": [
      "Sal",
      "Bamboo"
    ],
    "reason_category": "mining",
    "reason_detail": "Trees felled or cleared for Limestone mining lease in Palamu Tiger Reserve Fringe",
    "project_name": "Limestone mining lease",
    "authority": "Private lease",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Palamu%20Tiger%20Reserve%20Fringe%20Limestone%20mining%20lease%20India%20trees%20news&hl=en-IN",
    "source_type": "crowdsourced",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000087",
    "created_at": "2026-01-03T08:29:10.268Z",
    "lat": 26.08,
    "lng": 91.68,
    "location_name": "Guwahati Deepor Beel Fringe",
    "state": "Assam",
    "district": "Kamrup Metro",
    "tree_count": 234,
    "species": [
      "Wetland trees",
      "Bamboo"
    ],
    "reason_category": "real_estate",
    "reason_detail": "Trees felled or cleared for Guwahati smart city fill in Guwahati Deepor Beel Fringe",
    "project_name": "Guwahati smart city fill",
    "authority": "GMDA",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "no_clearance",
    "ngt_case": "NGT/2023/000156",
    "source_url": "https://www.google.com/search?q=Guwahati%20Deepor%20Beel%20Fringe%20Guwahati%20smart%20city%20fill%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "halted"
  },
  {
    "id": "00000000-0000-0000-0000-000000000088",
    "created_at": "2025-07-17T08:29:10.268Z",
    "lat": 26.95,
    "lng": 94.17,
    "location_name": "Majuli River Island",
    "state": "Assam",
    "district": "Majuli",
    "tree_count": 156,
    "species": [
      "Neem",
      "Bamboo"
    ],
    "reason_category": "disaster_clearance",
    "reason_detail": "Trees felled or cleared for Erosion control embankment in Majuli River Island",
    "project_name": "Erosion control embankment",
    "authority": "Water Resources Assam",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Majuli%20River%20Island%20Erosion%20control%20embankment%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000089",
    "created_at": "2025-11-14T08:29:10.268Z",
    "lat": 21.52,
    "lng": 70.52,
    "location_name": "Girnar Forest Foothills",
    "state": "Gujarat",
    "district": "Junagadh",
    "tree_count": 178,
    "species": [
      "Babul",
      "Neem"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Girnar ropeway approach in Girnar Forest Foothills",
    "project_name": "Girnar ropeway approach",
    "authority": "Tourism Dept Gujarat",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Girnar%20Forest%20Foothills%20Girnar%20ropeway%20approach%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000090",
    "created_at": "2026-02-12T08:29:10.268Z",
    "lat": 23.85,
    "lng": 70.2,
    "location_name": "Kutch Banni Grassland Fringe",
    "state": "Gujarat",
    "district": "Kutch",
    "tree_count": 67,
    "species": [
      "Acacia",
      "Prosopis"
    ],
    "reason_category": "power_infra",
    "reason_detail": "Trees felled or cleared for Renewable energy park in Kutch Banni Grassland Fringe",
    "project_name": "Renewable energy park",
    "authority": "GUVNL",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Kutch%20Banni%20Grassland%20Fringe%20Renewable%20energy%20park%20India%20trees%20news&hl=en-IN",
    "source_type": "rti",
    "contributor_id": null,
    "verified": false,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000091",
    "created_at": "2025-09-15T08:29:10.268Z",
    "lat": 26.12,
    "lng": 85.38,
    "location_name": "Muzaffarpur Orchard Belt",
    "state": "Bihar",
    "district": "Muzaffarpur",
    "tree_count": 890,
    "species": [
      "Litchi",
      "Mango"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for NH-28 Expansion in Muzaffarpur Orchard Belt",
    "project_name": "NH-28 Expansion",
    "authority": "NHAI",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "cleared",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Muzaffarpur%20Orchard%20Belt%20NH-28%20Expansion%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  },
  {
    "id": "00000000-0000-0000-0000-000000000092",
    "created_at": "2025-12-04T08:29:10.268Z",
    "lat": 30.72,
    "lng": 79.6,
    "location_name": "Valley of Flowers Approach",
    "state": "Uttarakhand",
    "district": "Chamoli",
    "tree_count": 89,
    "species": [
      "Rhododendron",
      "Oak"
    ],
    "reason_category": "road_widening",
    "reason_detail": "Trees felled or cleared for Hemkund pilgrimage road in Valley of Flowers Approach",
    "project_name": "Hemkund pilgrimage road",
    "authority": "PWD Uttarakhand",
    "ministry": "Ministry of Environment, Forest and Climate Change",
    "clearance_status": "under_review",
    "ngt_case": null,
    "source_url": "https://www.google.com/search?q=Valley%20of%20Flowers%20Approach%20Hemkund%20pilgrimage%20road%20India%20trees%20news&hl=en-IN",
    "source_type": "news",
    "contributor_id": null,
    "verified": true,
    "media_urls": null,
    "status": "ongoing"
  }
];
